/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/predictions'
    | '/profile'
    | '/reports'
    | '/students'
    | '/subjects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/predictions'
    | '/profile'
    | '/reports'
    | '/students'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/predictions'
    | '/profile'
    | '/reports'
    | '/students'
    | '/subjects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PredictionsRoute: typeof PredictionsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  StudentsRoute: typeof StudentsRoute
  SubjectsRoute: typeof SubjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PredictionsRoute: PredictionsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  StudentsRoute: StudentsRoute,
  SubjectsRoute: SubjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
